### ISSUE TITLE
大佬，这个自己部署在线人数统计，能否提供一个教程呢？谢谢！

### ISSUE THREAD

**Issue by kuhehe** [soxft/time-counter#4]
大佬，这个自己部署在线人数统计，能否提供一个教程呢？谢谢！
完全看不懂代码，谢谢！

**Comment by soxft** [comment]
有 wiki 的

https://github.com/soxft/time-counter/wiki/usage

https://github.com/soxft/time-counter/wiki/install

可以先参考一下
